main.yml updated

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: Final QA Automation Project WorkFlow
+name: CI/CD Pipeline
 
 on:
   push:
@@ -8,20 +8,19 @@ on:
     branches:
       - main
 
-jobs: 
+jobs:
   source:
     runs-on: ubuntu-latest
-    steps: 
-      - name: Check out repository code #Get source code
-        uses: actions/checkout@v4
-      
-      - name: Upload the code
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Upload code
         uses: actions/upload-artifact@v4
         with:
           name: code
           path: .
           retention-days: 1
-  
+
   build:
     needs: source
     runs-on: ubuntu-latest
@@ -37,6 +36,32 @@ jobs:
           name: code
           path: .
 
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.10.4'
+          cache: 'pip'
+
+      - name: Install dependencies
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install --upgrade pip
+          if [ -f "./backend/requirements.txt" ]; then
+            pip install -r ./backend/requirements.txt
+          else
+            echo "Error: requirements.txt not found in ./backend"
+            exit 1
+          fi
+
+      - name: Install npm packages and rub build command
+        run: |
+          cd ./frontend
+          npm install
+          npm run build
+          rm -rf node_modules
+
+      # Cache the virtual environment instead of uploading it as an artifact
       - name: Cache virtual environment
         uses: actions/cache@v3
         with:
@@ -45,32 +70,12 @@ jobs:
           restore-keys: |
             venv-${{ runner.os }}-
 
-      - name: Set up python 3.12
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.12'
-          cache: 'pip'
-
-      - name: Install dependencies
-        run: |
-          python -m venv .venv
-          source .venv/bin/activate
-          pip install --upgrade pip
-          pip install -r requirements.txt
-          
-            
-      - name: Install npm and run build
-        run: |
-          cd ./frontend
-          npm install
-          npm run build
-          rm -rf node_modules
-
-      - name: Upload the code
+      - name: Upload code
         uses: actions/upload-artifact@v4
         with:
           name: code
           path: .
+          overwrite: true
           retention-days: 1
 
   test:
@@ -85,24 +90,46 @@ jobs:
           name: code
           path: .
 
-      - name: Set up python 3.12
+      - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.12'
+          python-version: '3.10.4'
           cache: 'pip'
 
+      # Restore the cached virtual environment
       - name: Cache virtual environment
         uses: actions/cache@v3
         with:
           path: .venv
           key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
           restore-keys: |
-            venv-${{ runner.os }}-   
+            venv-${{ runner.os }}-
+      
+      # - name: build docker image and run container
+      #   run: |
+      #     docker build --build-arg PUBLIC_URL="http://localhost:8000/" -t backend .
+      #     docker run --rm -d -p 8000:8000 -e PUBLIC_URL="http://localhost:8000/" --name backend backend
 
+      # - name: Install test dependencies
+      #   run: |
+      #     source .venv/bin/activate
+      #     set -ex
+      #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+      #     sudo apt install ./google-chrome-stable_current_amd64.deb
+      #     python -m pip install --upgrade pip
+      #     cd ./backend
+      #     pip install -r requirements.txt
+      
       - name: Run tests
         run: |
-            source .venv/bin/activate
-            pytest tests/ --html-report=./report/report.html 
+          source .venv/bin/activate
+          cd ./frontend
+          npm install
+          npm run build:local
+          cd ../backend
+          python manage.py collectstatic --noinput
+          python manage.py runserver &
+          pytest --html-report=./report/report.html --title='PYTEST REPORT'
       
       - name: Upload test report
         id: upload-test-report
@@ -111,8 +138,7 @@ jobs:
         with:
           name: test-report
           path: ./backend/report
-      
-      
+
   deploy:
     if: success()
     needs: test
@@ -126,7 +152,7 @@ jobs:
 
       - name: Build Docker Image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-django-react:latest .
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-and-react-js-blog:latest .
 
       - name: Login and Push Docker Image
         run: |
@@ -141,76 +167,196 @@ jobs:
       #     render-api-key: ${{ secrets.RENDER_TOKEN }}
       #     wait-for-deployment: true
 
-  notify:
-    if: failure()
-    needs: test
-    runs-on: ubuntu-latest
-    steps:
-      
-      - name: Download test report
-        uses: actions/download-artifact@v4
-        with:
-          name: report.html
-          path: ./report
-      
-      - name: Deploy report to github pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./report
+          
+      # - name: Send Slack Notification
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     status: custom
+      #     custom_payload: |
+      #       {
+      #         "title": ":tada: Build successfull, deployed to Render.com",
+      #         "text": "You can view the live site at <https://blog-and-react-js-blog-latest.onrender.com/>",
+      #         "color": "#36a64f",
+      #         "fields": [
+      #           {
+      #             "title": "Live Site",
+      #             "value": "<https://blog-and-react-js-blog-latest.onrender.com/>",
+      #             "short": false
+      #           }
+      #         ],
+      #         "footer": "Render.com",
+      #         "footer_icon": "https://avatars.githubusercontent.com/u/41908446?s=200&v=4"
+      #       }
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
-      - name: Send notification
-        run: |
-          echo "Tests failed, sending notification to developers."
+  # notify:
+  #   if: failure()
+  #   needs: test
+  #   runs-on: ubuntu-latest
+  #   steps:
       
-      - name: Send Slack notification
-        uses: 8398a7/action-slack@v3
-        with:
-          status: custom
-          custom_payload: |
-            {
-              text: "Tests failed",
-              attachments: [{
-                "author_name": "github actions", // json
-                fallback: 'fallback',
-                color: 'danger',
-                title: 'CI Result',
-                text: 'The test job failed. Please check the logs on the GitHub Actions page for more details.',
-                fields: [],
-                actions: []
-              },
-              {
-                title: 'Test Report Zip',
-                text: 'The test report is attached as a zip file.',
-                fields: [],
-                actions: [],
-                title_link: '${{ needs.test.outputs.artifact-url }}',
-                footer: '',
-                footer_icon: '',
-                image_url: '',
-                thumb_url: '',
-                author_name: '',
-                author_link: '',
-                author_icon: '',
-                video_html: '',
-                video_url: '',
-              },
-              {
-                title: 'Test Report Url',
-                text: 'The test report is attached as a url to github pages.',
-                fields: [],
-                actions: [],
-                title_link: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report.html',
-                footer: '',
-                footer_icon: '',
-                image_url: '',
-                thumb_url: '',
-                author_name: '',
-                author_link: '',
-                author_icon: '',
-                video_html: '',
-                video_url: '',
-              }]
-            }        
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #     - name: Download test report
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: test-report
+  #         path: ./report
+      
+  #     - name: Deploy report to github pages
+  #       uses: peaceiris/actions-gh-pages@v3
+  #       with:
+  #         github_token: ${{ secrets.GITHUB_TOKEN }}
+  #         publish_dir: ./report
+
+  #     - name: Send notification
+  #       run: |
+  #         echo "Tests failed, sending notification to developers."
+      
+  #     - name: Send Slack notification
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         custom_payload: |
+  #           {
+  #             text: "Tests failed",
+  #             attachments: [{
+  #               "author_name": "github actions", // json
+  #               fallback: 'fallback',
+  #               color: 'danger',
+  #               title: 'CI Result',
+  #               text: 'The test job failed. Please check the logs on the GitHub Actions page for more details.',
+  #               fields: [],
+  #               actions: []
+  #             },
+  #             {
+  #               title: 'Test Report Zip',
+  #               text: 'The test report is attached as a zip file.',
+  #               fields: [],
+  #               actions: [],
+  #               title_link: '${{ needs.test.outputs.artifact-url }}',
+  #               footer: '',
+  #               footer_icon: '',
+  #               image_url: '',
+  #               thumb_url: '',
+  #               author_name: '',
+  #               author_link: '',
+  #               author_icon: '',
+  #               video_html: '',
+  #               video_url: '',
+  #             },
+  #             {
+  #               title: 'Test Report Url',
+  #               text: 'The test report is attached as a url to github pages.',
+  #               fields: [],
+  #               actions: [],
+  #               title_link: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report.html',
+  #               footer: '',
+  #               footer_icon: '',
+  #               image_url: '',
+  #               thumb_url: '',
+  #               author_name: '',
+  #               author_link: '',
+  #               author_icon: '',
+  #               video_html: '',
+  #               video_url: '',
+  #             }]
+  #           }        
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      
+      # - name: Send Slack notification
+      #   uses: 8398a7/action-slack@v3
+      #   with:
+      #     status: custom
+      #     custom_payload: |
+      #       {
+      #         text: "Tests failed",
+      #         attachments: [{
+      #           "author_name": "github actions", // json
+      #           fallback: 'fallback',
+      #           color: 'danger',
+      #           title: 'CI Result',
+      #           text: 'The test job failed. Please check the logs on the GitHub Actions page for more details.',
+      #           fields: [],
+      #           actions: []
+      #         },
+      #         {
+      #           title: 'Test Report',
+      #           text: 'The test report is attached as a file.',
+      #           fields: [],
+      #           actions: [],
+      #           title_link: '${{ needs.test.outputs.artifact-url }}',
+      #           footer: '',
+      #           footer_icon: '',
+      #           image_url: '',
+      #           thumb_url: '',
+      #           author_name: '',
+      #           author_link: '',
+      #           author_icon: '',
+      #           video_html: '',
+      #           video_url: '',
+      #         }]
+      #       }        
+      #   env:
+      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+      
+      # - name: Send email notification
+      #   uses: dawidd6/action-send-mail@master
+      #   with:
+      #     server_address: smtp.gmail.com
+      #     server_port: 587
+      #     username: ${{ secrets.EMAIL_USERNAME }}
+      #     password: ${{ secrets.EMAIL_PASSWORD }}
+      #     subject: "CI/CD Pipeline Failed"
+      #     to: ${{ secrets.EMAIL_TO }}
+      #     from: ${{ secrets.EMAIL_FROM }}
+      #     body: |
+      #       The CI/CD pipeline has failed. Please check the logs for more details.
+      #       Test Report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report.html
+      #       Test Report Zip: ${{ needs.test.outputs.artifact-url }}
+
+      # - name: Login to Jira
+      #   uses: atlassian/gajira-login@v3
+      #   env:
+      #     JIRA_BASE_URL: ${{ secrets.JIRA_ACCOUNT_URL }}
+      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USERNAME }}
+      #     JIRA_API_TOKEN: ${{ secrets.JIRA_PASSWORD }}
+      
+      # - name: Create Jira issue
+      #   id: create
+      #   uses: atlassian/gajira-create@v3
+      #   with:
+      #     project: '${{ vars.JIRA_PROJECT_KEY }}'
+      #     issuetype: 'Bug'
+      #     summary: 'CI/CD Pipeline Failed'
+      #     description: |
+      #       The CI/CD pipeline has failed. Please check the logs for more details.
+      #       [Test Report Zip](${{ needs.test.outputs.artifact-url }})
+      #       You can also view the test report on github pages
+      #       [Test Report Url](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report.html)
+          
+      # - name: Log created issue
+      #   run: echo "Issue ${{ steps.create.outputs.issue }} was created"
+
+      # - name: Open Jira issue
+      #   uses: bryannice/gitactions-jira-issue-creation@master
+      #   env:
+      #     JIRA_ACCOUNT_URL: ${{ secrets.JIRA_ACCOUNT_URL }}
+      #     JIRA_API_TOKEN: ${{ secrets.JIRA_PASSWORD }}
+      #     # JIRA_ISSUE_ATTACHMENT: log_file.log
+      #     JIRA_ISSUE_DESCRIPTION: 'The CI/CD pipeline has failed. Please check the logs for more details. [Test Report](${{ needs.test.outputs.artifact-url }})'
+      #     JIRA_ISSUE_SUMMARY: 'CI/CD Pipeline Automatic Tests Failed'
+      #     JIRA_ISSUE_TYPE: 'Bug'
+      #     JIRA_PROJECT: ${{ secrets.JIRA_PROJECT_KEY }}
+      #     JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
+          
+      # - name: Open GitHub issue
+      #   uses: actions/github-script@v6
+      #   with:
+      #     script: |
+      #       github.rest.issues.create({
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         title: 'CI/CD Pipeline Failed',
+      #         body: 'The CI/CD pipeline has failed. Please check the logs for more details. [Test Report](${{ needs.test.outputs.artifact-url }})'
+      #       })  
